import{a as u,S as v,i}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();u.defaults.baseURL="https://pixabay.com/api/";const M="44023316-0d50012e2ff9db94e7166d7a8";async function f(t,o=1){return(await u.get("",{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".js-load-more-btn"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:n,largeImageURL:c,tags:e,likes:r,views:a,comments:w,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${c}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
          <div class="info">
            <p><b>Likes</b>${r}</p>
            <p><b>Views</b>${a}</p>
            <p><b>Comments</b>${w}</p>
            <p><b>Downloads</b>${q}</p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),E.refresh()}function $(){m.innerHTML=""}function h(){p.classList.add("is-active")}function b(){p.classList.remove("is-active")}function L(){g.classList.remove("is-hidden")}function S(){g.classList.add("is-hidden")}let l="",s=1,d=0;const B=document.querySelector(".form");B.addEventListener("submit",R);const P=document.querySelector(".js-load-more-btn");P.addEventListener("click",j);document.querySelector(".js-gallery");document.querySelector(".js-loader");async function R(t){if(t.preventDefault(),l=t.currentTarget.elements["search-text"].value.trim(),l===""){i.warning({massage:"Please enter a search query.",position:"topRight"});return}s=1,$(),S(),h();try{const o=await f(l,s);o.hits.length===0?i.error({message:"Sorry, no images found!",position:"topRight"}):(y(o.hits),d=Math.ceil(o.totalHits/15),s<d&&L())}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{b(),t.target.reset()}}async function j(){s+=1,S(),h();try{const t=await f(l,s);y(t.hits),O(),s>=d?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch{i.error({message:"Error loading more images!",position:"topRight"})}finally{b()}}function O(){const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
